#!/bin/bash
#SBATCH --job-name=parallelBloom_job
#SBATCH --time=00:20:00
#SBATCH --mem=16G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --output=parBloom.%j.out
#SBATCH --partition=defq
if [ ! -f parBloom ]
then
    gcc parallelBloom.c -lm -lpthread -fopenmp -o parBloom
else
    if [ parBloom.c -nt parBloom ]
    then
        gcc parallelBloom.c -lm -lpthread -fopenmp -o parBloom
    fi
fi
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
./parBloom
exit 0